services:
  armadan:
    image: ghcr.io/caarvid/armadan:latest
    container_name: armadan
    restart: always
    env_file: ../.env
    environment:
      - PORT=8080
      - APP_ENV=production
    volumes:
      - /srv/armadan/data:/data:rw
    expose:
      - "8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/armadan/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /srv/armadan/ssl:/etc/letsencrypt:ro
      - /srv/armadan/www:/var/www/certbot:ro
    depends_on:
      - armadan
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /srv/armadan/ssl:/etc/letsencrypt
      - /srv/armadan/www:/var/www/certbot

networks:
  app-network:
    driver: bridge
