#!/usr/bin/env bash

info() {
    echo -e "\n\033[1;34m[INFO]\033[0m $1"
}

error() {
    echo -e "\n\033[1;31m[ERROR]\033[0m $1"
}

# Run any file generation
info "Generating files..."
if ! make hooks/pre-commit; then
    error "Generating files failed. Commit aborted."
    exit 1
fi

# Check code formatting
info "Checking code formatting..."
if ! gofmt -l .; then
    error "Code is not properly formatted. Please run 'gofmt' and try again."
    exit 1
fi

exit 0
