// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: password_reset_tokens.sql

package schema

import (
	"context"
)

const createToken = `-- name: CreateToken :one
INSERT INTO password_reset_tokens (token, user_id, expires_at) VALUES (?, ?, ?) RETURNING id, token, expires_at, user_id
`

type CreateTokenParams struct {
	Token     string `json:"token"`
	UserID    string `json:"userId"`
	ExpiresAt string `json:"expiresAt"`
}

func (q *Queries) CreateToken(ctx context.Context, arg *CreateTokenParams) (PasswordResetToken, error) {
	row := q.queryRow(ctx, q.createTokenStmt, createToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.UserID,
	)
	return i, err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM password_reset_tokens WHERE user_id = ?
`

func (q *Queries) DeleteToken(ctx context.Context, userID string) error {
	_, err := q.exec(ctx, q.deleteTokenStmt, deleteToken, userID)
	return err
}

const getToken = `-- name: GetToken :one
SELECT id, token, expires_at, user_id FROM password_reset_tokens WHERE token = ?
`

func (q *Queries) GetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.queryRow(ctx, q.getTokenStmt, getToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.UserID,
	)
	return i, err
}
