// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package schema

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCourse(ctx context.Context, arg *CreateCourseParams) (Course, error)
	CreateHoles(ctx context.Context, arg []*CreateHolesParams) (int64, error)
	CreatePlayer(ctx context.Context, arg *CreatePlayerParams) (Player, error)
	CreatePost(ctx context.Context, arg *CreatePostParams) (Post, error)
	CreateResult(ctx context.Context, weekID uuid.UUID) (Result, error)
	CreateRound(ctx context.Context, arg *CreateRoundParams) (Round, error)
	CreateScores(ctx context.Context, arg []*CreateScoresParams) (int64, error)
	CreateSession(ctx context.Context, arg *CreateSessionParams) (UserSession, error)
	CreateTees(ctx context.Context, arg []*CreateTeesParams) (int64, error)
	CreateToken(ctx context.Context, arg *CreateTokenParams) (PasswordResetToken, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (User, error)
	CreateWeek(ctx context.Context, arg *CreateWeekParams) (Week, error)
	DeleteCourse(ctx context.Context, id uuid.UUID) error
	DeletePlayer(ctx context.Context, id uuid.UUID) error
	DeletePost(ctx context.Context, id uuid.UUID) error
	DeleteResult(ctx context.Context, id uuid.UUID) error
	DeleteRound(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, token string) error
	DeleteTee(ctx context.Context, id uuid.UUID) error
	DeleteToken(ctx context.Context, userID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteWeek(ctx context.Context, id uuid.UUID) error
	GetCourse(ctx context.Context, id uuid.UUID) (GetCourseRow, error)
	GetCourses(ctx context.Context) ([]GetCoursesRow, error)
	GetLeaderboard(ctx context.Context) ([]GetLeaderboardRow, error)
	GetLeaderboardSummary(ctx context.Context, dollar_1 uuid.UUID) ([]GetLeaderboardSummaryRow, error)
	GetManageResultView(ctx context.Context) ([]GetManageResultViewRow, error)
	GetPlayer(ctx context.Context, dollar_1 uuid.UUID) (GetPlayerRow, error)
	GetPlayers(ctx context.Context) ([]GetPlayersRow, error)
	GetPost(ctx context.Context, id uuid.UUID) (Post, error)
	GetPosts(ctx context.Context) ([]Post, error)
	GetRemainingPlayersByResultId(ctx context.Context, resultID uuid.UUID) ([]Player, error)
	GetResultById(ctx context.Context, id uuid.UUID) (GetResultByIdRow, error)
	GetRoundsByResultId(ctx context.Context, resultID uuid.UUID) ([]GetRoundsByResultIdRow, error)
	GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error)
	GetTeesByCourse(ctx context.Context, courseID uuid.UUID) ([]Tee, error)
	GetToken(ctx context.Context, hash string) (PasswordResetToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	GetWeek(ctx context.Context, dollar_1 uuid.UUID) (WeekDetail, error)
	GetWeeks(ctx context.Context) ([]WeekDetail, error)
	UpdateCourse(ctx context.Context, arg *UpdateCourseParams) (Course, error)
	UpdateHoles(ctx context.Context, arg []*UpdateHolesParams) *UpdateHolesBatchResults
	UpdatePlayer(ctx context.Context, arg *UpdatePlayerParams) (Player, error)
	UpdatePost(ctx context.Context, arg *UpdatePostParams) (Post, error)
	UpdateTees(ctx context.Context, arg []*UpdateTeesParams) *UpdateTeesBatchResults
	UpdateUserEmail(ctx context.Context, arg *UpdateUserEmailParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg *UpdateUserPasswordParams) (User, error)
	UpdateUserRole(ctx context.Context, arg *UpdateUserRoleParams) (User, error)
	UpdateWeek(ctx context.Context, arg *UpdateWeekParams) (Week, error)
}

var _ Querier = (*Queries)(nil)
