// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tees.sql

package schema

import (
	"context"

	"github.com/google/uuid"
)

const getTeesByCourse = `-- name: GetTeesByCourse :many
SELECT id, name, slope, cr, course_id FROM tees WHERE course_id = $1
`

func (q *Queries) GetTeesByCourse(ctx context.Context, courseID uuid.UUID) ([]Tee, error) {
	rows, err := q.db.Query(ctx, getTeesByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tee
	for rows.Next() {
		var i Tee
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slope,
			&i.Cr,
			&i.CourseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
