name: CI

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup go"
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"
      - run: |
          go get ./.. 
          go build -o ./dist/armadan ./cmd/armadan/main.go

      - name: "Login to ghcr.io"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/caarvid/armadan

      - name: "Build and push"
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: BUILD_VERSION=${{ github.ref_name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
